services:
  - type: web
    name: shl-recommender-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      export PYTHONPATH=src && uvicorn src.app:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: PYTHONPATH
        value: "src"
    instances: 1
