services:
  - type: web
    name: shl-recommender
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.app:app --host=0.0.0.0 --port=10000
    envVars:
      - key: PYTHONPATH
        value: src
